# Generated by Django 2.1.5 on 2019-01-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
